### Create new patient
POST http://localhost:4004/api/patients
Content-Type: application/json

{
  "name": "Yash Suri",
  "email": "yashsuri1999@gmail.com",
  "address": "17-A, Ujjawal",
  "dateOfBirth": "1999-12-31",
  "registeredDate": "2025-09-01"
}

###