### GET request to example server
PUT http://localhost:4004/api/patients/123e4567-e89b-12d3-a456-426614174000
Content-Type: application/json

{
  "name": "Yash Suri",
  "email": "yashsuri1999@gmail.com",
  "address": "17-A, Ujjawal",
  "dateOfBirth": "1999-12-31"
}

###